### ISSUE TITLE
Missing referenced secure file azure-aks-node-ssh-key.pub

### ISSUE THREAD

**Issue by terrytsay** [Azure/osdu-infrastructure#10]
This secure file azure-aks-node-ssh-key.pub referenced in ```aksAgentSshPublicKeyFilename: 'azure-aks-node-ssh-key.pub'``` from [/devops/infrastructure/prepare-stage.yml](https://github.com/Azure/osdu-infrastructure/blob/master/devops/infrastructure/prepare-stage.yml) is not present in /scripts/.ssh.

The public key generated is **azure-aks-gitops-ssh-key.pub**

Therefore, this will cause the build to fail until either the file name or the referenced name is changed.

**Comment by danielscholl** [comment]
This has been resolved now and merged into the master branch. Thanks for calling this out.
