### ISSUE TITLE
The Key Vault that contains the partition properties needs to be moved to the common resource group

### ISSUE THREAD

**Issue by vtarasov4** [Azure/osdu-infrastructure#104]
Moving the Key Vault (KV) from the services resource group (RG) to the common RG is going to help to keep the KV and the partition properties if the services RG is recreated.

Acceptance criteria:
- New Key Vault is created using the `common_resources` manifest.
- Only available properties (Elasticsearch credentials etc.) should be stored in the common Key Vault. Other secrets (Cosmos DB etc.) should be added during the data partition setup (#103).
- The existing Key Vault should not be removed from `service_resources` at this point because of the current activities related to deployment of the services, it will be cleaned up later.

**Comment by danielscholl** [comment]
Please document the Acceptance Criteria as well as if you plan on implementing this in multiple steps, would be good to know what the sequence flow might be of activities.

**Comment by vtarasov4** [comment]
@danielscholl, sure, I've added the acceptance criteria.

**Comment by danielscholl** [comment]
The common KV is now merged and we can start to duplicate keys.  As part of the PR I updated the architecture picture so it would be clearer what architecture we are moving towards.

Please See the diagram [here](https://github.com/Azure/osdu-infrastructure/tree/master/infra/templates/osdu-r3-resources).
