### ISSUE TITLE
Store partition properties using the Partition service API

### ISSUE THREAD

**Issue by vtarasov4** [Azure/osdu-infrastructure#105]
Partition service is updated to delegate the secret handling to the service. This change requires some updates:
- Azure table storage will be utilized to store partition info.
- Non-sensitive and sensitive properties will be stored in table storage for the partition, non-sensitive ones are going to be stored with values. This can be achieved by a Partition service API call (POST request).

**Comment by ashley-kelham** [comment]
The scope of this would include deploying the partition service as part of the infrastructure deployment stages and then using the partition service to save partition properties rather than using key vault directly during the data resource group provisioning

**Comment by danielscholl** [comment]
I'm not sure what this issue actually is and what is being requested of the infrastructure. Please add additional information or close.

**Comment by vtarasov4** [comment]
@danielscholl, we've updated the description according to the recent updates in the Partition service. And we'll share more information about the API soon.

**Comment by danielscholl** [comment]
I believe this item is completed now.
