### ISSUE TITLE
Dynamic deployment of the new data partitions needs to be supported (multipartition setup)

### ISSUE THREAD

**Issue by vtarasov4** [Azure/osdu-infrastructure#106]
TBD

**Comment by ashley-kelham** [comment]
The scope of this is to allow partitions to be created and destroyed on demand by the OSDU deployment itself rather than as part of the ADO pipelines. This will eventually allow clients of the system to be in control of partition creation/deletion.

**Comment by danielscholl** [comment]
I'm not sure what this issue actually is and what is being requested of the infrastructure.  Please add additional information or close.

**Comment by ashley-kelham** [comment]
This is needed in Q4 and isn't the immediate priority. We need to allow for new partitions to be deployed after the initial deployment of an OSDU environment. This could even be triggered by the customer. We are still working out the full workflow.

**Comment by danielscholl** [comment]
This feature/code has fully migrated now to GitLab.
