### ISSUE TITLE
Entitlement Service Service Principal Is not authorized to call ReadAll for GraphAPI

### ISSUE THREAD

**Issue by daniakodeih** [Azure/osdu-infrastructure#11]
Service Principal Needs granted access to the following Graph APIs.

Directory.Read.All
User.Read.All

This change has to occur in the service-principal module which currently looks like the following.

resource "azuread_application" "sp" {
  count = local.sps_to_create
  name  = var.display_name
}

This means that support in the module for resources are not built into the module yet.  The resource needs to have a section that looks somewhat like the following which is pulled from the ad-application module.

required_resource_access {
    resource_app_id = var.resource_app_id

    resource_access {
      id   = var.resource_role_id
      type = var.resource_access_type
    }
  }

You can see that this only supports then 1 Resource Type, but we have multiple.  It will have to be extended to look more like the following.

dynamic "required_resource_access" {
    for_each = local.required_resource_access

    content {
      resource_app_id = required_resource_access.value.resource_app_id

      dynamic "resource_access" {
        for_each = required_resource_access.value.resource_access

        content {
          id   = resource_access.value.id
          type = resource_access.value.type
        }
      }
    }
  }

**Comment by danielscholl** [comment]
This issue is actually a feature requirement necessary to support additional API's for Entitlements.  Entitlements has the need to be able to access MS Graph API and the service principal being used needs privileges to retrieve information from this API.

**Comment by danielscholl** [comment]
@daniakodeih This feature has been successfully added to the infrastructure.
