### ISSUE TITLE
Deploying additional partitions using the R3 infrastructure

### ISSUE THREAD

**Issue by vtarasov4** [Azure/osdu-infrastructure#118]
Deployment of additional partitions needs to be supported. The first step and the intermediate implementation is going to include a way to store additional partition properties in the common Key Vault using prefixes for the new partitions. ConfigMap changes are out of scope of the initial implementation and will be done as the next step. The partition that's used now in a single-partition setup will not be removed or changed to make sure that the current setup works as expected.

**Comment by danielscholl** [comment]
This effort is now a project and there need to be subtasks or issues divided and separated out.

https://github.com/Azure/osdu-infrastructure/projects/4
