### ISSUE TITLE
Support autoscale on ComosDB deployment configuration

### ISSUE THREAD

**Issue by ashley-kelham** [Azure/osdu-infrastructure#127]
Currently the CosmosDB deployment uses the 'Defined Throughput' configuration which means we have to set a defined RU limit and always pay for this maximum usage. DE by nature has usage in short high bursts. This means this configuration would be very costly for us.

We would like to be able to define the Autoscale option on CosmosDB deployments and set the max RUs we would like to scale up to for a partition.

I would like to be able to define the max RUs differently for every partition.

**Comment by danielscholl** [comment]
@ashley-kelham Can you give an example perhaps of what you are thinking that you would like to see, or how you think you would like to be able to configure things?

**Comment by ashley-kelham** [comment]
This is the configuration I would like to be able to set

https://docs.microsoft.com/en-us/azure/cosmos-db/provision-throughput-autoscale

We would need to be able to set that 'autoscale throughput' is being used on a CosmosDb database (I'm not convinced we'll need to set this at a container level, at least not yet, maybe in the future). We would then need to define the max R/Us that the database can scale to

So when declaring a cosmosdb instance being able to set something like the below.

...

   throughput_type: 'autoscale | defined'
   throughput_max: 1000
}

 I'm not sure if the terraform module exposes defining this yet. Currently the 'type' is always 'defined'

**Comment by danielscholl** [comment]
This feature has been implemented as part of another PR.  https://github.com/Azure/osdu-infrastructure/pull/159/files

```
# Database Settings
cosmosdb_consistency_level = "Session"
cosmos_databases = [
  {
    name       = "test-db"
    throughput = 1100
  }
]
cosmos_sql_collections = [
  {
    name               = "SharedThroughput"
    database_name      = "osdu-db"
    partition_key_path = "/id"
    throughput         = 0
  },
  {
    name               = "DedicatedThroughput"
    database_name      = "osdu-db"
    partition_key_path = "/id"
    throughput         = 400
  }
]
```

**Comment by ashley-kelham** [comment]
This is good. Does it also support autoscale? 

The configuration shown looks like switching a container to have a dedicated throughput  or sharing the throughput with all containers with the cosmosdb deployment. 

Is there a different value for 'name' we can define for autoscale or am I misreading it?

**Comment by ashley-kelham** [comment]
@danielscholl  I don't think I have permission to re-open issues closed by a collaborator. Can you?

We believe this can be configured without creating a new database instance because you can change this configuration in the portal on an existing Cosmos deployment but we have to verify this.
