### ISSUE TITLE
Add support for additional Services

### ISSUE THREAD

**Issue by danielscholl** [Azure/osdu-infrastructure#134]
The following needs to be added to support additional services being onboarded.

__Storage Container__
- [x]  osdu-wks-mappings

__Database Collections__
- [x] Authority
- [x] EntityType
- [x] SchemaInfo
- [x] Source

__Service Bus__
- [x] recordstopic

  - wkssubscription

__AppGw Ingress Controller__
- [x] update ingress controller to add context path for schema service

__Istio Auth__
- [x] add Authorization policy for schema service

Acceptance Criteria
--------------------
Unit Tests Pass
Integration Tests Pass

**Comment by danielscholl** [comment]
This Issue was originally submitted only by a PR.  Typically an Issue should be created first so that we know what the purpose of the PR is for.

Unfortunately due to a misunderstanding on how Pipelines fire the PR was approved and merged into master but Unit Tests were failing which blocked migration through additional environments.  

#133 Is attempting to fix this by removing the Subscription code and sending the Storage and DB changes out then later followup only with a SB Subscription change on the Topic.

FYI @polavishnu4444

**Comment by danielscholl** [comment]
@polavishnu4444 -- We need 1 more PR that attempts to do the following.

Add the Service Bus change.

** We need to ensure the following tests pass prior to PR and Merge **
1.  Test Private Instance of configuration that is currently deployed at master branch can make the change.
2.  Test Private Instance of configuration that has never been deployed can make the change.
3.   Unit Tests pass
4.   Integration Tests pass

> There may be a bug in the module that prohibits the task from being accomplished.

**Comment by imran-siddique** [comment]
@polavishnu4444 - Are we good to close this?

**Comment by danielscholl** [comment]
Closing this issue as completed.
