### ISSUE TITLE
Configure Airflow for use

### ISSUE THREAD

**Issue by danielscholl** [Azure/osdu-infrastructure#138]
Airflow is required in order to support the Ingest Workstream.  An initial PR #130 was submitted which will need to be broken up into smaller tasks and PR's and tracked here in this Issue.

- [x] Add Support for Storage File Shares and Storage Queues in the Storage Module.

- [x] Add (DAG) Storage into the osdu-mvp architecture.

- [x] Add (DAG) Storage into the osdu-r3-resources architecture.

- [x] Update the osdu-common helm chart kv-secrets.yaml to add in secrets for Reds, Postgres, and DAG Storage.

**Comment by danielscholl** [comment]
@catweisun Storage for Airflow is added to OSDU-mvp architecture.

**Comment by imran-siddique** [comment]
@NickKarsky - Where are we tracking the file service work?

**Comment by danielscholl** [comment]
This issue has been completed as part of osdu-mvp architecture.
