### ISSUE TITLE
Data partition Id needs to be used for key vault secrets prefix

### ISSUE THREAD

**Issue by ashley-kelham** [Azure/osdu-infrastructure#144]
Currently a 5 character string is used to define the partition in the infrastructure deployment.  This is needed so that it can be assigned to Azure resources created to uniquely name them for each partition.

However the data partition id can be up to 30 characters. Anything created that needs to be used at runtime will need to use the data partition id to uniquely name it so that the services can understand what partition it belongs to.

The key vault IDs stored will need to use the data partition id as the prefix.

I would like to be able to define a mapping during partition deployment between the 5 character string and the data partition id and have the data partition id be used for the key vault IDs secrets

**Comment by danielscholl** [comment]
This is already covered by the following use case of osdu-mvp.  https://github.com/Azure/osdu-infrastructure/tree/master/infra/templates/osdu-r3-mvp#3-data-partition-key-vault-value-naming

Please review the implementation and if it doesn't meet requirements we can raise a bug.
