### ISSUE TITLE
SDMS needs a separate storage account in R3 partition

### ISSUE THREAD

**Issue by ashley-kelham** [Azure/osdu-infrastructure#168]
Due to the quotas and limits imposed on a storage account 

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#storage-limits

We will need a second one provisioned to be used only by the SDMS service as this will potentially hold petabytes of data in some situations and could also hit ingress and egress limits.

**Comment by danielscholl** [comment]
Is this part of Data Partition?  I need a list of requirements to go with this.

1.  Storage Account Type
2. Storage Containers needed
3. Naming convention of keys in KV or no keys necessary.
4. How will the Storage account be accessed.  What identity policies are necessary.
5. What Roles need to be created to those identities.

**Comment by varungbt** [comment]
Storage account type: StorageV2
Storage container: Blob storage container 
Naming convention for keys in KV: nothing specific
Storage account is accessed using a pod identity. The user managed identity associated with this pod identity has storage blob data contributor role.

**Comment by danielscholl** [comment]
This has been added.
