### ISSUE TITLE
Manual infrastructure updates were needed in the pre-MVP setup

### ISSUE THREAD

**Issue by vtarasov4** [Azure/osdu-infrastructure#180]
Some manual updates were needed in the recent version of the R3 setup (pre-MVP). These updates helped to make sure that the deployed services worked as expected, and that integration tests were passing:
- Set Cosmos DB connection string as a "servicebus" secret in OSDU namespace. Primary key was set there. 
- Had to set storage account from the the service resource group as 'ENV_STORAGE_DIAGNOSTICS' instead of a storage account from data group.

@danielscholl, can you please let us know if you faced these issues? We'd be glad to know if the manual updates are going to be needed when the MVP version is set up.

**Comment by danielscholl** [comment]
This feature/code has fully migrated to GitLab.
