### ISSUE TITLE
The default gitops_path value is used even if the corresponding environment variable is set

### ISSUE THREAD

**Issue by vtarasov4** [Azure/osdu-infrastructure#185]
At this point the [default gitops_path value](https://github.com/Azure/osdu-infrastructure/blob/master/infra/templates/osdu-r3-mvp/service_resources/variables.tf) is used if the path env. variable is set. This needs to be changed to make sure that Flux can use the same manifest repository for different environments.

**Comment by danielscholl** [comment]
Item is closed.
