### ISSUE TITLE
Need to Add Entitlement for Delivery Service for Integration Tester

### ISSUE THREAD

**Issue by jsangiamo** [Azure/osdu-infrastructure#205]
Currently, the integration tester is not granted any entitlements for the delivery service (see https://github.com/Azure/osdu-infrastructure/blob/master/docs/osdu/integration-test-data/user_info_1.json). This causes delivery service integration tests to fail until those entitlements are granted. The entitlement that needs to be added is service.delivery.viewer (see https://community.opengroup.org/osdu/platform/system/delivery/-/blob/master/delivery-core/src/main/java/org/opengroup/osdu/delivery/api/DeliveryApi.java#L53). 

Outstanding questions
1. Does this need to be added for both tenants?
2. Are there any other permissions that need to be granted to run the delivery integration tests?

**Comment by danielscholl** [comment]
This feature/code has fully migrated to GitLab.
