### ISSUE TITLE
Error with passphrase if ssh-keys already exists in Install.sh

### ISSUE THREAD

**Issue by janmortensen** [Azure/osdu-infrastructure#21]
The function CreateSSHKeys will cause the script to end and throw an error message IF the SSH-keys already exists. It will try to AddKeyToVault for PASSPHRASE, but the passphrase is only generated if the files does not exist. 

Maybe either test for which scenario is happening or move the AddKeyToVault into the check-area?

**Comment by danielscholl** [comment]
Fixed with PR #40
