### ISSUE TITLE
Does a Service Principal used by Terraform in this solution need AAD Graph API with AD Application Read Write?

### ISSUE THREAD

**Issue by njain5-slb** [Azure/osdu-infrastructure#43]
Terraform code to setup the infrastructure for Core services has a pre-requisite on AAD Graph api, which are going to be retired in 2022. Terraform code should be updated to use Microsoft Graph Apis instead.

**Comment by danielscholl** [comment]
@njain5-slb Where do you see a pre-requisite in this project for ADD Graph API.  I'm not exactly aware of where this may exist.

**Comment by njain5-slb** [comment]
@danielscholl please go here and check the prerequisite section: https://github.com/Azure/osdu-infrastructure/tree/master/infra/templates/osdu-r3-resources

**Comment by danielscholl** [comment]
Okay for the R2 implementation Service Principals and Applications are being created by Terraform.  As defined by Project Cobalt the Service Principal as documented [here](https://github.com/Azure/osdu-infrastructure/blob/master/infra/templates/osdu-r2-resources/README.md#prerequisites) should use AAD Graph API AD Application Read Write.  I'm not sure at the moment as I haven't validated it if MS Graph API Application Read Write would work exactly the same.  My thinking is that the answer is yes and it is just a documentation change that would be necessary.

**Comment by danielscholl** [comment]
This issue should now be addressed and answered by #132 and is being closed.
