### ISSUE TITLE
Unique number generation install.sh script stuck

### ISSUE THREAD

**Issue by jortkoopmans** [Azure/osdu-infrastructure#6]
When running the install.sh script and not providing a 'unique' number yourself; the random generator is stuck.
Seems to be related to not ending the urandom output at any time (process keeps going).
Result is that the install script is 'stuck' without any visual output.

**Comment by danielscholl** [comment]
Are you using a Mac or WSL Ubuntu?  The script uses /dev/urandom.

**Comment by jortkoopmans** [comment]
Hi @danielscholl , thanks for reviewing. I'm using the Azure Cloud CLI, not sure what that's based on. But /dev/urandom works fine, generating lots of output (continuously). The issue is that the process is never completed and the set of piped commands is 'stuck' processing urandom forever (= not completing with 3 random digits). I hope this is clarified from the PR as well.

**Comment by danielscholl** [comment]
This has been resolved decided to use UNIQUE=$(echo $((RANDOM%999+100)))
