### ISSUE TITLE
Missing steps to set up permissions for assigning roles

### ISSUE THREAD

**Issue by terrytsay** [Azure/osdu-infrastructure#9]
The steps to create Service Connection (Step 3+4 from Configure Azure DevOps) only creates with Contributor role. User Access Administrator (or something that grants permission to create role assignments) is also needed because terraform script is doing a lot of azurerm_role_assignment.

The documentation should include steps to assign a least privilege role to allow role assignments

**Comment by danielscholl** [comment]
@terrytsay Thanks a lot for adding this item.  I believe this should now be more clear with our updated documentation.
