### ISSUE TITLE
Configure Istio to the R3 Template

### ISSUE THREAD

**Issue by kiranveerapaneni** [Azure/osdu-infrastructure#95]
The R3 template design is to utilize ISTIO for Authentication. This needs to be configured into the infrastructure and be deployed as part of the infrastructure template.

Acceptance Criteria
All tests should pass.
Istio should be able to Run and configure Auth rules.

Tasks
- [x] Install Istio 1.4 with Helm Charts
- [x] Upgrade/Install Istio 1.6 
- [x] Configure Rules with YAML template
- [x]  Configure RequestAuthentication
- [x]  Configure PeerAuthentication.

**Comment by danielscholl** [comment]
@kiranveerapaneni -- This is completed I believe.  Can we close this Issue yet?

**Comment by danielscholl** [comment]
Closing this issue as completed.
