### ISSUE TITLE
Test Istio on AKS, with entitlements service.

### ISSUE THREAD

**Issue by polavishnu4444** [Azure/osdu-infrastructure#96]
Using Istio configured rules we can test the authentication done by Istio.

- [x] Entitlement service with Istio rules.
- [x] Another deployment of Entitlements service without its authentication and relying on Istio input headers post authentication. 
- [x] Legal service with peer authentication to communicate with entitlements.

**Comment by danielscholl** [comment]
@polavishnu4444 -- This issue is completed I believe.  Can we close it?

**Comment by danielscholl** [comment]
Closing this issue as completed.
